name: Java CI

on:
  push:
    branches:
      - master
  schedule:
    # Every day at 3am
    - cron: '0 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup WALA
      run: ./setup_deps

    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Run basic tests
      run: ant -noinput -buildfile build.xml joana.api.test
    - uses: actions/upload-artifact@v2
      with:
        name: joana.api.jar
        path: ./dist/joana.api.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.ifc.sdg.core.jar
        path: ./dist/joana.ifc.sdg.core.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.ifc.sdg.qifc.nildumu.jar
        path: ./dist/joana.ifc.sdg.qifc.nildumu.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.ui.ifc.sdg.graphviewer.jar
        path: ./dist/joana.ui.ifc.sdg.graphviewer.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.ui.ifc.wala.cli.jar
        path: ./dist/joana.ui.ifc.wala.cli.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.ui.ifc.wala.console.jar
        path: ./dist/joana.ui.ifc.wala.console.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.wala.core.jar
        path: ./dist/joana.wala.core.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.wala.dictionary.jar
        path: ./dist/joana.wala.dictionary.jar
    - uses: actions/upload-artifact@v2
      with:
        name: joana.wala.jodroid.jar
        path: ./dist/joana.wala.jodroid.jar
